### ISSUE TITLE
NCN5121 Schematic

### ISSUE THREAD

**Issue by dzungpv** [Chrismettal/PiPLC#1]
I want to ask more about NCN5121.
You design not mention in the datasheet. So in your design use are using external 3.3v to power the chip and not using any of LDO and on chip DC/DC. And the ground for the Pi and KNX the same, but the difference in the voltage.
Do you test it in real life? Because I have the same schematic but I use DC/DC converter 1 to power the chip and connected with Pi by common ground (TX, RX and GND to Pi), but sometime it cause data error.

**Comment by Chrismettal** [comment]
You are correct, the NC5121 design used in PiPLC is not one of the application examples listed in the NCN5121 datasheet.

I am not using the on-board DC/DC as I already have all the voltages required present and don't need to supply any of PiPLC from the usually pretty limited KNX supplies. They are helpful when designing a device that lives parasitically only from KNX but with this design it didn't make sense to draw power from the KNX.

It would have made sense to keep the NCN5121 running from KNX power and having the Pi be isolated through a UART isolator but that's something for another version.

The design is proven and is currently running in 3 deployed systems. I did not yet see any data loss and can reliably read and write from/to the KNX with the design as implemented.

**Comment by dzungpv** [comment]
> You are correct, the NC5121 design used in PiPLC is not one of the application examples listed in the NCN5121 datasheet.
> 
> I am not using the on-board DC/DC as I already have all the voltages required present and don't need to supply any of PiPLC from the usually pretty limited KNX supplies. They are helpful when designing a device that lives parasitically only from KNX but with this design it didn't make sense to draw power from the KNX.
> 
> It would have made sense to keep the NCN5121 running from KNX power and having the Pi be isolated through a UART isolator but that's something for another version.
> 
> The design is proven and is currently running in 3 deployed systems. I did not yet see any data loss and can reliably read and write from/to the KNX with the design as implemented.

Thank you for the information.

**Comment by dzungpv** [comment]
@Chrismettal I make KNX adapter for Pi4b base on your schematics with some modified, but it not working. I tested the board with Siemens N148 and it work (I using knx stack and try to program it with ETS), so not the hardware issue.

But when I install it to the Pi4b with KNXD add-on follow your guide here [interface-ncn5120] Link down](https://github.com/Chrismettal/PiPLC?tab=readme-ov-file#wago-header--knx--ncn5121) for Home Assistance it not working: show error:

```
F00000105: [15:interface-ncn5120] Link down, terminating
```

I also try usb driver and tpuart driver still the same.

My config:

```
address: 15.15.1
client_address: 15.15.2:8
interface: nc5120
log_error_level: warning
usb_filters: single
dest_port: "99"
device: /dev/ttyAMA0
baudrate: 19200
```

Can you share your working config?

**Comment by Chrismettal** [comment]
Have you followed the guide to enable NC5120 communication on the Pi?

![image](https://github.com/user-attachments/assets/d198b547-edde-4af0-ab94-77642b77eaa9)

You can also try installing knxd in bare linux on the pi without HASS to debug your system. Might be easier than going through the KNXd addon first.

This is my working config:

```
address: 0.0.1
client_address: 0.0.2:8
interface: ncn5120
device: /dev/ttyAMA0
log_error_level: warning
usb_filters: single
ip_address: 0.0.0.0
dest_port: "99"
custom_config: ""
```

**Comment by dzungpv** [comment]
> Have you followed the guide to enable NC5120 communication on the Pi?
> 
> ![image](https://private-user-images.githubusercontent.com/39636046/386622454-d198b547-edde-4af0-ab94-77642b77eaa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzgzMjYsIm5iZiI6MTczMTY3ODAyNiwicGF0aCI6Ii8zOTYzNjA0Ni8zODY2MjI0NTQtZDE5OGI1NDctZWRkZS00YWYwLWFiOTQtNzc2NDJiNzdlYWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEzNDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMDliN2MxNDI0MWJhZDQxMjY0MzE2YjM2MDM1NWI5OGQzMWM4MjdjM2RjODQ0ZDAyZTk0NDYxZWEwN2M2MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-F5_C2m2_6bwofiWnMA2uwc6g22CZMhzUfSunhbDQRU)
> 
> You can also try installing knxd in bare linux on the pi without HASS to debug your system. Might be easier than going through the KNXd addon first.
> 
> This is my working config:
> 
> ```
> address: 0.0.1
> client_address: 0.0.2:8
> interface: ncn5120
> device: /dev/ttyAMA0
> log_error_level: warning
> usb_filters: single
> ip_address: 0.0.0.0
> dest_port: "99"
> custom_config: ""
> ```

Yes, This is my hardware information in HA:
![image](https://github.com/user-attachments/assets/d7fcb24f-409e-4509-bd46-c6a8b6205cf7)

I also try UART4, the same. I use add-on version 0.5.2

**Comment by dzungpv** [comment]
It working now, because tty not disable on the HA, I read this issue  and do some additional command to disable it and it work https://github.com/knxd/knxd/issues/514
